apiVersion: apps/v1
kind: Deployment
metadata:
  name: grupa-w-chmurze-back-end-deployment
  labels:
    app: grupa-w-chmurze-back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grupa-w-chmurze-back-end
  template:
    metadata:
      name: grupa-w-chmurze-back-end
      labels:
        app: grupa-w-chmurze-back-end
    spec:
      containers:
        - name: grupa-w-chmurze-back-end-container
          image: grupawchmurzebackendacrregestry.azurecr.io/grupa-w-chmurze-back-end:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI

---

apiVersion: v1
kind: Service
metadata:
  name: grupa-w-chmurze-back-end-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: grupa-w-chmurze-back-end